#                  _
#  __ _ _ __   __ _| |_   _ _______
# / _` | '_ \ / _` | | | | |_  / _ \
#| (_| | | | | (_| | | |_| |/ /  __/
#\__,_|_| |_|\__,_|_|\__, /___\___|
#                    |___/
name: 'Analyze PR Python'
description: 'Analyze Pull request Python'
inputs:
  vul_threshold:
    description: "Vulnerability risk score threshold value"
    required: true
  mal_threshold:
    description: "Malicious Code risk score threshold value"
    required: true
  eng_threshold:
    description: "Engineering risk score threshold value"
    required: true
  lic_threshold:
    description: "License risk score threshold value"
    required: true
  aut_threshold:
    description: "Author risk score threshold value"
    required: true
  phylum_username_in:
    description: "Phylum username"
    required: true
  phylum_password_in:
    description: "Phylum password"
    required: true

runs:
  using: "composite"
  steps:
    - id: phylum-test
      uses: peterjmorgan/install-phylum-latest-action@master
      with:
        phylum_username: ${{ inputs.phylum_username_in }}
        phylum_password: ${{ inputs.phylum_password_in }}
    - name: Check for existing project
      run: |
        result=$(find . -maxdepth 1 -iname ".phylum_project")
        if [[ -n $result ]]; then
          echo "Phylum project found: $result"
        else
          echo "[ERROR] Phylum project file not found"
          exit 11
        fi

