#                  _
#  __ _ _ __   __ _| |_   _ _______
# / _` | '_ \ / _` | | | | |_  / _ \
#| (_| | | | | (_| | | |_| |/ /  __/
#\__,_|_| |_|\__,_|_|\__, /___\___|
#                    |___/
name: 'Analyze PR Python'
description: 'Analyze Pull request Python'
inputs:
  vul_threshold:
    description: "Vulnerability risk score threshold value"
    required: true
  mal_threshold:
    description: "Malicious Code risk score threshold value"
    required: true
  eng_threshold:
    description: "Engineering risk score threshold value"
    required: true
  lic_threshold:
    description: "License risk score threshold value"
    required: true
  aut_threshold:
    description: "Author risk score threshold value"
    required: true
  phylum_username_in:
    description: "Phylum username"
    required: true
  phylum_password_in:
    description: "Phylum password"
    required: true

runs:
  using: "composite"
  steps:
    - id: phylum-test
      uses: peterjmorgan/install-phylum-latest-action@master
      with:
        phylum_username: ${{ inputs.phylum_username_in }}
        phylum_password: ${{ inputs.phylum_password_in }}
    - name: Check for existing project
      shell: bash
      run: |
        result=$(find . -maxdepth 1 -iname ".phylum_project")
        if [[ -n $result ]]; then
          echo "Phylum project found: $result"
        else
          echo "[ERROR] Phylum project file not found"
          exit 11
        fi

    - name: Check and set GITHUB_HEAD_REF env variable
      shell: bash
      run: |
        if [[ -z $GITHUB_HEAD_REF ]]; then
          echo "GITHUB_HEAD_REF isn't set"
          echo GITHUB_HEAD_REF="refs/thingy/master" >> $GITHUB_ENV
        else
          echo "GITHUB_HEAD_REF is set: ${GITHUB_HEAD_REF}"
        fi

    - name: Generate Phylum label
      shell: bash
      run: |
        echo PHYLUM_LABEL="GHA-PR${PR_NUM}-${GITHUB_HEAD_REF}" >> $GITHUB_ENV
        echo "PHYLUM_LABEL = ${PHYLUM_LABEL}"

    - name: Analyze project lockfile
      shell: bash
      run: |
        export PATH="$HOME/.phylum:$PATH"
        pushd $GITHUB_WORKSPACE || exit 11
          phylum analyze -l $PHYLUM_LABEL requirements.txt --verbose --json > ~/phylum_analysis.json
          echo "[*] Analyzed requirements.txt under label ${PHYLUM_LABEL} and wrote results to ~/phylum_analysis.json"
        popd

    - uses: technote-space/get-diff-action@v4
      with:
        FILES: |
          requirements.txt
          #pyproject.toml

    - name: Get requirements.txt git diff
      shell: bash
      run: git diff --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} > ~/DIFF
      if: env.GIT_DIFF
